package com.bengisusahin.odev_10.view

import android.content.Intent
import android.os.Bundle
import android.widget.Toast
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.lifecycle.lifecycleScope
import com.bengisusahin.odev_10.R
import com.bengisusahin.odev_10.configs.AppDatabase
import com.bengisusahin.odev_10.databinding.ActivitySignupBinding
import com.bengisusahin.odev_10.models.User
import com.bengisusahin.odev_10.repository.UserRepository
import kotlinx.coroutines.launch

class SignupActivity : AppCompatActivity() {

    private lateinit var binding: ActivitySignupBinding
    private lateinit var userRepository: UserRepository
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivitySignupBinding.inflate(layoutInflater)
        enableEdgeToEdge()
        setContentView(binding.root)
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main)) { v, insets ->
            val systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom)
            insets
        }

        val database = AppDatabase(this)
        val userDao = database.userDao()
        userRepository = UserRepository(userDao)

        binding.signUpButton.setOnClickListener {
            val username = binding.textUsername.text.toString()
            val password = binding.textPassword.text.toString()
            lifecycleScope.launch {
                signUp(username, password)
            }
        }

        binding.textviewLogin.setOnClickListener {
            val intent = Intent(this, LoginActivity::class.java)
            startActivity(intent)
            finish()
        }
    }

    // sign up the user with the given username and password
    private suspend fun signUp(username: String, password: String) {
        if (username.isEmpty() || password.isEmpty()) {
            Toast.makeText(this, "Please fill in all fields", Toast.LENGTH_SHORT).show()
            return
        }else{
            // id will be auto-generated by the database
            val user = User(id = 0, username = username, password = password)
            val effectRow = userRepository.insertUser(user)
            if (effectRow != -1L) {
                // user added successfully
                Toast.makeText(this, "User signed up successfully", Toast.LENGTH_SHORT).show()
                val intent = Intent(this, LoginActivity::class.java)
                startActivity(intent)
                finish()
            } else {
                // user could not be added
                Toast.makeText(this, "User could not be signed up", Toast.LENGTH_SHORT).show()
            }
        }
    }
}